CREATE TABLE `banner_full` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`REPORT_DATE` VARCHAR(50) NOT NULL DEFAULT '0',
	`STORE_BKEY` VARCHAR(100) NOT NULL DEFAULT '0',
	`BANNER_NAME` VARCHAR(100) NOT NULL DEFAULT '0',
	`STORE_TYPE` VARCHAR(100) NOT NULL DEFAULT '0',
	`PRODUCT_BKEY` VARCHAR(100) NOT NULL DEFAULT '0',
	`BRAND_NAME` VARCHAR(100) NOT NULL DEFAULT '0',
	`AMOUNT_PER_KG` FLOAT NOT NULL DEFAULT '0',
	`PRICE_PER_KG` FLOAT NOT NULL DEFAULT '0',
	`HAS_GROUND` INT(11) NOT NULL DEFAULT '0',
	`WEEK_OF_YEAR` INT(11) NOT NULL DEFAULT '0',
	`MONTH_OF_YEAR` INT(11) NOT NULL DEFAULT '0',
	`YEAR_OF_WEEK` INT(11) NOT NULL DEFAULT '0',
	`IS_VALENTINE` INT(11) NOT NULL DEFAULT '0',
	`IS_TEACHER` INT(11) NOT NULL DEFAULT '0',
	`IS_C_VALENTINE` INT(11) NOT NULL DEFAULT '0',
	`IS_CHILDREN` INT(11) NOT NULL DEFAULT '0',
	`IS_NEWYEAR` INT(11) NOT NULL DEFAULT '0',
	`IS_CHRISTMAS` INT(11) NOT NULL DEFAULT '0',
	`IS_12` INT(11) NOT NULL DEFAULT '0',
	`IS_11` INT(11) NOT NULL DEFAULT '0',
	`IS_618` INT(11) NOT NULL DEFAULT '0',
	`IS_SUMMER` INT(11) NOT NULL DEFAULT '0',
	`IS_WINTER` INT(11) NOT NULL DEFAULT '0',
	`STORE_COUNT` INT(11) NOT NULL DEFAULT '0',
	`CITY_COUNT` INT(11) NOT NULL DEFAULT '0',
	`RN` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	INDEX `id` (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
